[package]
name = "gba-rs"
version = "0.1.0"
authors = ["Sean Purcell <me@seanp.xyz>"]

[dependencies]
byteorder = "^1.2.2"
clap = "2"
log = "^0.4.1"
env_logger = "^0.5.6"
maplit = "^1.0.1"
memmap = "^0.6.2"
sdl2 = "0.31.0"
